repository/urls.py
"""
URL patterns for Repository
"""

from django.conf.urls.defaults import *
import repository.views as views
import repository.views.base
import repository.views.data
import repository.views.task
import repository.views.method
import repository.views.challenge
import repository.views.ajax
import repository.views.publication
import repository.forms as forms

urlpatterns = patterns('',
    # index
    url(r'^$', views.base.main_index, name='repository_index'),

    # search
    url(r'^search/$', views.base.search, name='repository_search'),

    # tags
    url(r'^tags/data/(?P<tag>[A-Za-z0-9-_.!]+)/$', views.data.tags_view, name='data_tags_view'),
    url(r'^tags/task/(?P<tag>[A-Za-z0-9-_.!]+)/$', views.task.tags_view, name='task_tags_view'),
    url(r'^tags/method/(?P<tag>[A-Za-z0-9-_.!]+)/$', views.method.tags_view, name='method_tags_view'),
    url(r'^tags/challenge/(?P<tag>[A-Za-z0-9-_.!]+)/$', views.challenge.tags_view, name='challenge_tags_view'),

    # data, tasks, methods, challenges
    (r'^data/', include('mldata.repository.data_urls')),
    (r'^task/', include('mldata.repository.task_urls')),
    (r'^method/', include('mldata.repository.method_urls')),
    (r'^challenge/', include('mldata.repository.challenge_urls')),

    # publications
    url(r'^publication/edit/$', views.publication.edit, name='publication_edit'),
    url(r'^publication/get/(?P<id>\d+)/$', views.publication.get, name='publication_get'),

    # upload progress AJAX
    (r'^upload_progress/$', views.ajax.upload_progress),
)

urls.py
from django.conf.urls import *
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import views

urlpatterns = patterns('',
    (r'^about/', include('about.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^forum/', include('forum.urls')),
    (r'^repository/', include('repository.urls')),

    # somewhat util
    #(r'^accounts/', include('registration.urls')),
    (r'^accounts/', include('django_authopenid.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^user/', include('user.urls')),
    (r'^datacite/', include('datacite.urls')),
    (r'^challenge/', include('challengeviewer.urls')),

    (r'^$', views.welcome),
)

if settings.DEBUG and not settings.PRODUCTION:
	urlpatterns += patterns('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media'}),)

data/models.py
from django.db import models
from django.db.models import Q
from repository.models import Repository
from repository.models import License

from settings import DATAPATH

from repository.models import Rating

from tagging.fields import TagField
from tagging.models import Tag
from tagging.models import TaggedItem
from tagging.utils import calculate_cloud

from utils import slugify

import ml2h5
import os

class Data(Repository):
    """Repository item Data.

    @cvar source: source of the data
    @type source: string / models.CharField
    @cvar format: data format of original file, e.g. CSV, ARFF, HDF5
    @type format: string / models.CharField
    @cvar measurement_details: item's measurement details
    @type measurement_details: string / models.TextField
    @cvar usage_scenario: item's usage scenario
    @type usage_scenario: string / models.TextField
    @cvar file: data file
    @type file: models.FileField
    @cvar license: license of Data item
    @type license: License
    @cvar is_approved: is_approved is necessary for 2-step creation, don't want to call review ever again once the item is approved - review can remove permanently via 'Back' button!
    @type is_approved: boolean / models.BooleanField
    @cvar num_instances: number of instances in the Data file
    @type num_instances: integer / models.IntegerField
    @cvar num_attributes: number of attributes in the Data file
    @type num_attributes: integer / models.IntegerField
    @cvar tags: item's tags
    @type tags: string / tagging.TagField
    """
    source = models.TextField(blank=True)
    format = models.CharField(max_length=16)
    measurement_details = models.TextField(blank=True)
    usage_scenario = models.TextField(blank=True)
    file = models.FileField(upload_to=DATAPATH)
    license = models.ForeignKey(License)
    is_approved = models.BooleanField(default=False)
    num_instances = models.IntegerField(blank=True, default=-1)
    num_attributes = models.IntegerField(blank=True, default=-1)
    tags = TagField() # tagging doesn't work anymore if put into base class


    def get_filename(self):
        """Construct filename for Data file.

        @return: filename for Data file
        @rtype: string
        @raise AttributeError: if slug is not set.
        """
        if not self.slug_id:
            raise AttributeError, 'Attribute slug is not set!'

        return self.slug.text + '.' + self.format

    def get_media_file_name(self):
        return os.path.join(MEDIA_ROOT, self.file.name)

    def approve(self, fname_orig, convdata):
        """Approve Data item.

        @param fname_orig: original name of Data file
        @type fname_orig: string
        @param convdata: conversion-relevant data
        @type convdata: dict of strings with keys seperator, convert, format + attribute_names_first
        @raise: ml2h5.converter.ConversionError if conversion failed
        """
        self.is_approved = True
        self.format = convdata['format']
        fname_h5 = ml2h5.fileformat.get_filename(fname_orig)

        if 'convert' in convdata and convdata['convert'] and self.format != 'h5':
            if 'attribute_names_first' in convdata and convdata['attribute_names_first']:
                anf = True
            else:
                anf = False

            verify = True
            if convdata['format'] == 'uci': verify = False

            try:
                c = ml2h5.converter.Converter(
                                              fname_orig, fname_h5, format_in=self.format,
                                              seperator=convdata['seperator'],
                                              attribute_names_first=anf
                                              )
                c.run(verify=verify)
            except ml2h5.converter.ConversionError, error:
                if self.tags:
                    self.tags += ', conversion_failed'
                else:
                    self.tags = 'conversion_failed'

                self.save()
                raise ml2h5.converter.ConversionError(error.value)

        if os.path.isfile(fname_h5):
            (self.num_instances, self.num_attributes) = ml2h5.data.get_num_instattr(fname_h5)
            # keep original file for the time being
            #os.remove(fname_orig)
            # for some reason, FileField saves file.name as DATAPATH/<basename>
            self.file.name = os.path.join(DATAPATH, fname_h5.split(os.path.sep)[-1])

        self.save()

    def attach_file(self, file_object):
        self.file = file_object

    @classmethod
    def get_query(cls, qs):
        return qs & Q(is_approved=True)

    def qs_for_related(self):
        return self.task_data

    def get_completeness_properties(self):
        return ['tags', 'description', 'license', 'summary', 'urls',
            'publications', 'source', 'measurement_details', 'usage_scenario']


class DataRating(Rating):
    """Rating for a Data item."""
    repository = models.ForeignKey(Data)

repository/models.py
"""
Model classes for app Repository
"""

from datetime import datetime as dt
from django.contrib.auth.models import User
from django.contrib.comments.models import Comment
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.utils.translation import ugettext as _
import ml2h5.data
import ml2h5.fileformat
import ml2h5.task
import random
from tagging.models import Tag
from tagging.models import TaggedItem
from tagging.utils import calculate_cloud
from utils import slugify

import repository

class Slug(models.Model):
    """Slug - URL-compatible item name.

    @cvar text: URL-compatible item name
    @type text: string / models.CharField
    """
    text = models.CharField(max_length=32, unique=True)

    def __unicode__(self):
        return unicode(self.text)


class License(models.Model):
    """License to be used by Data items.

    @cvar name: name of the license
    @type name: string / models.CharField
    @cvar url: url of the license
    @type url: string / models.CharField
    """
    name = models.CharField(max_length=255, unique=True)
    url = models.CharField(max_length=255)

    def __unicode__(self):
        return unicode(self.name)


class FixedLicense(models.Model):
    """License to be used by Task or Solution items.

    For some reason, it didn't work when just inheriting, so
    the code needs to be duplicated.

    @cvar name: name of the license
    @type name: string / models.CharField
    @cvar url: url of the license
    @type url: string / models.CharField
    """
    name = models.CharField(max_length=255, unique=True)
    url = models.CharField(max_length=255)

    def __unicode__(self):
        return unicode(self.name)


class Publication(models.Model):
    title = models.CharField(max_length=80)
#    slug = models.SlugField(unique=True)
    content = models.TextField()
#    firstauthor = models.CharField(max_length=256)
#    bibtype = models.CharField(max_length=256)
#    authors = models.CharField(max_length=2048)
#    year = models.IntegerField()
#    bibitem = models.TextField()
#    category = models.ForeignKey(Category)
#    abstract = models.TextField()
#    month = models.CharField(max_length=20, blank=True, null=True)
#    journal = models.CharField(max_length=256, blank=True, null=True)
#    number = models.CharField(max_length=256, blank=True, null=True)
#    institution = models.CharField(max_length=256, blank=True, null=True)
#    subcategory = models.ForeignKey('self', blank=True, null=True)
#    editor = models.CharField(max_length=2048, blank=True, null=True)
#    publisher = models.CharField(max_length=256, blank=True, null=True)
#    booktitle = models.CharField(max_length=256, blank=True, null=True)
#    pages = models.CharField(max_length=256, blank=True, null=True)
#    pdf = models.CharField(max_length=256, blank=True, null=True)
#    ps = models.CharField(max_length=256, blank=True, null=True)
#    url = models.CharField(max_length=256, blank=True, null=True)
#    note = models.CharField(max_length=256, blank=True, null=True)
#    pubtype = models.CharField(max_length=256, blank=True, null=True)
#    school = models.CharField(max_length=256, blank=True, null=True)
#    dataset = models.CharField(max_length=256, blank=True, null=True)
#    address = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        ordering = ('title', )

    def __unicode__(self):
        return self.title



class Repository(models.Model):
    """Base class for Repository items: Data, Task, Solution

    @cvar pub_date: publication date (item creation date)
    @type pub_date: models.DateTimeField
    @cvar version: version number to flip between different incarnations of the item
    @type version: integer / models.IntegerField
    @cvar name: item's name
    @type name: string / models.CharField
    @cvar slug: item's slug
    @type slug: string / Slug
    @cvar summary: item's summary
    @type summary: string / models.CharField
    @cvar description: item's description
    @type description: string / models.TextField
    @cvar urls: URLs linking to more information about item
    @type urls: string / models.CharField
    @cvar publications: publications where item is mentioned or used
    @type publications: models.ManyToManyField
    @cvar is_public: if item is public
    @type is_public: boolean / models.BooleanField
    @cvar is_deleted: if item is deleted
    @type is_deleted: boolean / models.BooleanField
    @cvar is_current: if item is the current one
    @type is_current: boolean / models.BooleanField
    @cvar user: user who created the item
    @type user: Django User
    @cvar rating_avg: item's average overal rating
    @type rating_avg: float / models.FloatField
    @cvar rating_avg_interest: item's average interesting rating
    @type rating_avg_interest: float / models.FloatField
    @cvar rating_avg_doc: item's average documentation rating
    @type rating_avg_doc: float / models.FloatField
    @cvar rating_votes: item's total number of rating votes
    @type rating_votes: integer / models.IntegerField
    """
    pub_date = models.DateTimeField()
    version = models.IntegerField(default=1)
    name = models.CharField(max_length=32)
    slug = models.ForeignKey(Slug)
    summary = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    urls = models.CharField(max_length=255, blank=True)
    publications = models.ManyToManyField(Publication, blank=True)
    is_public = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False, editable=False)
    is_current = models.BooleanField(default=False, editable=False)
    user = models.ForeignKey(User, related_name='repository_user')
    rating_avg = models.FloatField(editable=False, default=-1)
    rating_avg_interest = models.FloatField(editable=False, default=-1)
    rating_avg_doc = models.FloatField(editable=False, default=-1)
    rating_votes = models.IntegerField(editable=False, default=0)
    downloads = models.IntegerField(editable=False, default=0)
    hits = models.IntegerField(editable=False, default=0)

    class Meta:
        """Inner meta class to specify options.

        @cvar ordering: default ordering of items in queries
        @type ordering: list
        @cvar get_latest_by: latestness will be determined by this field
        @type get_latest_by: string
        """
        ordering = ('-pub_date', )
        get_latest_by = 'pub_date'

    @classmethod
    def get_current_tagged_items(cls, user, tag):
        """Get current items with specific tag.

        @param user: user to get current items for
        @type user: auth.models.user
        @param tag: tag to get tagged items for
        @type tag: tagging.Tag
        @return: current tagged items
        @rtype: list of Data, Task or Solution
        """
        # without if-construct sqlite3 barfs on AnonymousUser
        if user.id:
            qs = (Q(user=user) | Q(is_public=True)) & Q(is_current=True)
        else:
            qs = Q(is_public=True) & Q(is_current=True)
        qs = cls.get_query(qs)

        tagged = TaggedItem.objects.filter(tag=tag)
        current = cls.objects.filter(qs).order_by('name')
        items = []
        for c in current:
            for t in tagged:
                if t.object_id == c.id:
                    items.append(c)
                    break
        return items

    @classmethod
    def get_object(cls, slug_or_id, version=None):
        """Retrieves an item by slug or id

            @param slug_or_id: item's slug or id for lookup
            @type slug_or_id: string or integer
            @param version: specific version of the item to retrieve
            @type version: integer
            @return: found object or None
            @rtype: Repository
            """
        if version:
            obj = cls.objects.filter(slug__text=slug_or_id, is_deleted=False, version=version)
        else:
            obj = cls.objects.filter(slug__text=slug_or_id, is_deleted=False, is_current=True)

        if obj: # by slug
            obj = obj[0]
        else: # by id
            try:
                obj = cls.objects.get(pk=slug_or_id)
            except cls.DoesNotExist:
                return None
            if not obj or obj.is_deleted:
                return None

        return obj


    def __init__(self, * args, ** kwargs):
        super(Repository, self).__init__(*args, ** kwargs)
        self.pub_date = dt.now()

    def __unicode__(self):
        return unicode(self.name)

    def get_media_file_name(self):
        raise NotImplementedError

    @classmethod
    def get_query(cls, qs):
        """Get a query for the given query.

        This allows objects to add further query qualifications (currently,
        Data: &= Q(is_approved=True)
        """
        return qs

    def save(self):
        """Save item.

        Creates a slug if necessary.
        """
        if not self.slug_id:
            self.slug = self.make_slug()
        super(Repository, self).save()


    def delete(self):
        """Delete item.

        Delete the corresponding slug.
        """
        try:
            Slug.objects.get(pk=self.slug.id).delete()
        except Slug.DoesNotExist:
            pass


    def make_slug(self):
        """Make a slug generated for the item's name.

        @return: a slug
        @rtype: Slug
        @raise AttributeError: if item's name is not set
        """
        if not self.name:
            raise AttributeError, 'Attribute name is not set!'
        slug = Slug(text=slugify(self.name))
        slug.save()
        return slug


    def get_next_version(self):
        """Get next available version for this item.

        @return: next available version
        @rtype: integer
        """
        if not self.slug_id:
            raise AttributeError, 'Attribute slug is not set!'

repository/forms/publication.py
from django import forms
from repository.models import Publication

class PublicationForm(forms.ModelForm):
    """Form used for publications."""
    id = forms.IntegerField()
    next = forms.CharField()

    class Meta:
        """Inner meta class to specify model options.

        @cvar model: model to use
        @type model: models.Publication
        """
        model = Publication

repository/templates/repository/conversion_failed.html
{% if object.conversion_failed and not object.is_public %}
{% load i18n %}
<div id="conversion_failed">
<p class="error">
	{% trans "The conversion has failed. Your data is marked as private. You can edit dataset by clicking EDIT action or publish it anyway by clicking ACTIVATE (loosing permission to edit it afterwards). If you expirience further problems, please contact the administrator." %}<br />
</p>
</div>
{% endif %}

repository/templates/repository/data_edit.html
{% extends "repository/base.html" %}
{% load i18n %}

{% block title %}{% trans "Repository" %} :: {% trans "Data" %} :: {% trans "Edit" %}{% endblock %}
{% block billboard %}{% trans "Repository" %} :: {% trans "Data" %} :: {% trans "Edit" %}{% endblock %}

{% block extrahead %}
{% include "autocomplete.html" %}
<script type="text/javascript" src="/media/js/jquery/ui.core.js"></script>
<script type="text/javascript" src="/media/js/jquery/ui.tabs.js"></script>
<script type="text/javascript">
$(function() {
	$('#cancel').click(function() {
		window.history.back(-1);
	});

	$('#contents').tabs();
});
</script>
{% endblock %}

{% block content %}
<h1>{% trans "Edit Data for" %} {{ prev.name }} ({% trans "version " %}{{ prev.version }})</h1>

<form action="{% url repository.views.data_edit prev.id %}" method="post" enctype="multipart/form-data">
<div id="contents" class="widget">
<ul class="head">
	<li><a title="{% trans "Primary attributes of Data item + download" %}" href="#contents-main">{% trans "Main" %}</a></li>
	<li><a title="{% trans "Other attributes of Data item" %}" href="#contents-other">{% trans "Other" %}</a></li>
</ul>

<div id="contents-main">
	<div class="title"><label for="id_license">{% trans "License" %}</label> (<a href="../license">{% trans "more info" %}</a>) {{ form.license.errors }}</div>
	<div class="data">{{ form.license }}</div>
	<div class="title"><label for="id_tags">{% trans "Tags" %}</label> {{ form.tags.errors }}</div>
	<div class="data">{{ form.tags }}</div>
	<div class="title"><label for="id_description">{% trans "Description" %}</label> {{ form.description.errors }}</div>
	<div class="data">{{ form.description }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></div>
	<div class="title"><label for="id_is_public">{% trans "Is the Data item ready to be seen by the public" %}?</label> {{ form.is_public.errors }}</div>
	<div class="data">{{ form.is_public }}</div>
</div>

<div id="contents-other">
	<div class="title"><label for="id_summary">{% trans "Summary" %}</label> {{ form.summary.errors }}</div>
	<div class="data">{{ form.summary }}</div>
	<div class="title"><label for="id_urls">{% trans "URLs" %}</label> {{ form.urls.errors }}</div>
	<div class="data">{{ form.urls }}</div>
	<div class="title"><label for="id_publications">{% trans "Publications" %}</label> {{ form.publications.errors }}</div>
	<div class="data">{{ form.publications }}</div>
	<div class="title"><label for="id_source">{% trans "Data Source" %}</label> {{ form.source.errors }}</div>
	<div class="data">{{ form.source }}</div>
	<div class="title"><label for="id_measurement_details">{% trans "Measurement details" %}</label> {{ form.measurement_details.errors }}</div>
	<div class="data">{{ form.measurement_details }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></div>
	<div class="title"><label for="id_usage_scenario">{% trans "Usage scenario" %}</label> {{ form.usage_scenario.errors }}</div>
	<div class="data">{{ form.usage_scenario }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></div>
</div>

<p><input type="submit" id="post" name="post" class="submit-post" value="{% trans "Edit" %}" /> <input type="button" id="cancel" name="cancel" class="submit-post" value="{% trans "Cancel" %}" /></p>
</div>
</form>
{% endblock %}

repository/templates/repository/data_submit.html
{% extends "repository/base.html" %}
{% load i18n %}

{% block title %}{% trans "Repository" %} :: {% trans "Data" %} :: {{ title }}{% endblock %}

{% block billboard %}{% trans "Repository" %} :: {% trans "Data" %} :: {{ title }}{% endblock %}

{% block extrahead %}
{% include "autocomplete.html" %}
{% endblock %}

{% block content %}
<h1>{{ head }}</h1>

<form action="{{ action }}" method="post" enctype="multipart/form-data">
<table>
<tr>
{% if is_new %}
	<td style="vertical-align: top"><dl>
		<dd><label for="id_name">{% trans "Name" %}*:</label> {{ form.name.errors }}</dd>
		<dt>{{ form.name }}</dt>
		<dd><label for="id_file">{% trans "Data file" %}{% if is_new %}*{% endif %}:</label> {{ form.file.errors }}</dd>
		<dt>{{ form.file }}</dt>
		<dd><label for="id_format">{% trans "Data Format" %} (CSV, ARFF, HDF5, ...) *:</label> {{ form.format.errors }}</dd>
		<dt>{{ form.format }}</dt>
		<dd><label for="id_license">{% trans "License" %}</label> (<a href="../license">{% trans "more info" %}</a>): {{ form.license.errors }}</dd>
		<dt>{{ form.license }}</dt>
		<br />
		<dt><input type="submit" name="post" class="submit-post" value="{% trans "Submit Data" %}" /></td>
	</dl></td>
{% endif %}
	<td style="vertical-align: top"><dl>
{% if not is_new %}
		<dd><label for="id_license">{% trans "License" %}</label> (<a href="../license">{% trans "more info" %}</a>): {{ form.license.errors }}</dd>
		<dt>{{ form.license }}</dt>
{% endif %}
		<dd><label for="id_tags">{% trans "Tags" %}:</label> {{ form.tags.errors }}</dd>
		<dt>{{ form.tags }}</dt>
		<dd><label for="id_summary">{% trans "Summary" %}:</label> {{ form.summary.errors }}</dd>
		<dt>{{ form.summary }}</dt>
		<dd><label for="id_description">{% trans "Description" %}:</label> {{ form.description.errors }}</dd>
		<dt>{{ form.description }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dt>
		<dd><label for="id_urls">{% trans "URLs" %}:</label> {{ form.urls.errors }}</dd>
		<dt>{{ form.urls }}</dt>
		<dd><label for="id_publications">{% trans "Publications" %}:</label> {{ form.publications.errors }}</dd>
		<dt>{{ form.publications }}</dt>
		<dd><label for="id_is_public">{% trans "Is the Data ready to be seen by the public" %}?</label> {{ form.is_public.errors }}</dd>
		<dt>{{ form.is_public }}</dt>
		<dd><label for="id_source">{% trans "Data Source" %}:</label> {{ form.source.errors }}</dd>
		<dt>{{ form.source }}</dt>
		<dd><label for="id_measurement_details">{% trans "Measurement details" %}:</label> {{ form.measurement_details.errors }}</dd>
		<dt>{{ form.measurement_details }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dt>
		<dd><label for="id_usage_scenario">{% trans "Usage scenario" %}:</label> {{ form.usage_scenario.errors }}</dd>
		<dt>{{ form.usage_scenario }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dt>
		<br />
		<dt><input type="submit" name="post" class="submit-post" value="{% trans "Submit Data" %}" /></td>
	</dl></td>
</tr>
</table>
</form>
{% endblock %}

repository/templates/repository/hdf5.html
{% extends "repository/base.html" %}
{% load i18n %}

{% block title %}{% trans "Repository" %} :: HDF5{% endblock %}
{% block breadcrumbs %}<a href="{% url repository.views.index %}">{% trans "Repository" %}</a> / HDF5{% endblock %}

{% block content %}
<h2 class="title-01">{% trans "Our HDF5 Format Explained" %}</h2>
<div class="in">
	<p><a href="http://www.hdfgroup.org/HDF5/">HDF5</a> {% trans "is a data model, library, and file format for storing and managing data. It supports an unlimited variety of datatypes, and is designed for flexible and efficient I/O and for high volume and complex data. HDF5 is portable and is extensible, allowing applications to evolve in their use of HDF5. The HDF5 Technology suite includes tools and applications for managing, manipulating, viewing, and analyzing data in the HDF5 format." %}</p>
	<p>{% trans "Internally, we make use of HDF5 because of its hierarchical structure which allows for efficient access of data attributes. It also allows for storing data in a flexible way which seems paramount to us in the current state of the machine learning community and its wild bunch of file formats used." %}</p>

	<p>{% trans "We defined the following HDF5 attributes in our files" %}:</p>
	<ul>
		<li>mldata ({% trans "Internal mldata version, currently set to" %} 0)</li>
		<li>name ({% trans "Name to describe the item as found in the file" %})</li>
		<li>comment ({% trans "Any comment in the file" %})</li>
	</ul>

	<p>{% trans "The following datasets may be defined in our HDF5 files" %}:</p>
	<ul>
		<li>attribute_names ({% trans "Names of the data attributes" %})</li>
		<li>attribute_types ({% trans "Types of the data attributes" %})</li>
		<li>attributes ({% trans "The data attributes themselves" %})</li>
	</ul>
</div><!-- /in -->
{% endblock %}

repository/templates/repository/rating_hide.html
{% load show_stars %}
{% load i18n %}
<div id="rating-hide-title">
	<div style="float:left" id="rating-hide-head">{% trans "Rating" %}</div>
	<div style="float:right" id="rating-hide-close"><a href="#">X</a></div>
</div>
<div style="clear:both" id="rating-hide-results">
	<div><nobr>{% show_stars current.rating_avg of 5 round to half %}</nobr> {% trans "Overall" %} ({% trans "based on" %} {{ current.rating_votes }} {% trans "vote" %}{{ current.rating_votes|pluralize }})</div>
	<div><nobr>{% show_stars current.rating_avg_interest of 5 round to half %}</nobr> {% trans "Interesting" %}</div>
	<div><nobr>{% show_stars current.rating_avg_doc of 5 round to half %}</nobr> {% trans "Documentation" %}</div>
</div>
{% if rating_form %}
<div id="rating-hide-form">
	{% trans "Ratings can be changed later on, '0' means poor and '5' means excellent" %}.</p>
	<form method="post" action="{{ rating_form.action }}">
		<ul class="rating-form">
			{{ rating_form.as_ul }}
		</ul>
		<input type="submit" class="submit" value="{% trans "Submit ratings" %}">
        {% csrf_token %}
	</form>
</div>
{% endif %}