repository/urls.py
"""
URL patterns for Repository
"""

from django.conf.urls.defaults import *
import repository.views as views
import repository.views.base
import repository.views.data
import repository.views.task
import repository.views.method
import repository.views.challenge
import repository.views.ajax
import repository.views.publication
import repository.forms as forms

urlpatterns = patterns('',
    # index
    url(r'^$', views.base.main_index, name='repository_index'),

    # search
    url(r'^search/$', views.base.search, name='repository_search'),

    # tags
    url(r'^tags/data/(?P<tag>[A-Za-z0-9-_.!]+)/$', views.data.tags_view, name='data_tags_view'),
    url(r'^tags/task/(?P<tag>[A-Za-z0-9-_.!]+)/$', views.task.tags_view, name='task_tags_view'),
    url(r'^tags/method/(?P<tag>[A-Za-z0-9-_.!]+)/$', views.method.tags_view, name='method_tags_view'),
    url(r'^tags/challenge/(?P<tag>[A-Za-z0-9-_.!]+)/$', views.challenge.tags_view, name='challenge_tags_view'),

    # data, tasks, methods, challenges
    (r'^data/', include('mldata.repository.data_urls')),
    (r'^task/', include('mldata.repository.task_urls')),
    (r'^method/', include('mldata.repository.method_urls')),
    (r'^challenge/', include('mldata.repository.challenge_urls')),

    # publications
    url(r'^publication/edit/$', views.publication.edit, name='publication_edit'),
    url(r'^publication/get/(?P<id>\d+)/$', views.publication.get, name='publication_get'),

    # upload progress AJAX
    (r'^upload_progress/$', views.ajax.upload_progress),
)

urls.py
from django.conf.urls import *
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import views

urlpatterns = patterns('',
    (r'^about/', include('about.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^forum/', include('forum.urls')),
    (r'^repository/', include('repository.urls')),

    # somewhat util
    #(r'^accounts/', include('registration.urls')),
    (r'^accounts/', include('django_authopenid.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^user/', include('user.urls')),
    (r'^datacite/', include('datacite.urls')),
    (r'^challenge/', include('challengeviewer.urls')),

    (r'^$', views.welcome),
)

if settings.DEBUG and not settings.PRODUCTION:
	urlpatterns += patterns('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media'}),)

repository/models.py
"""
Model classes for app Repository
"""

from datetime import datetime as dt
from django.contrib.auth.models import User
from django.contrib.comments.models import Comment
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.utils.translation import ugettext as _
import ml2h5.data
import ml2h5.fileformat
import ml2h5.task
import random
from tagging.models import Tag
from tagging.models import TaggedItem
from tagging.utils import calculate_cloud
from utils import slugify

import repository

class Slug(models.Model):
    """Slug - URL-compatible item name.

    @cvar text: URL-compatible item name
    @type text: string / models.CharField
    """
    text = models.CharField(max_length=32, unique=True)

    def __unicode__(self):
        return unicode(self.text)


class License(models.Model):
    """License to be used by Data items.

    @cvar name: name of the license
    @type name: string / models.CharField
    @cvar url: url of the license
    @type url: string / models.CharField
    """
    name = models.CharField(max_length=255, unique=True)
    url = models.CharField(max_length=255)

    def __unicode__(self):
        return unicode(self.name)


class FixedLicense(models.Model):
    """License to be used by Task or Solution items.

    For some reason, it didn't work when just inheriting, so
    the code needs to be duplicated.

    @cvar name: name of the license
    @type name: string / models.CharField
    @cvar url: url of the license
    @type url: string / models.CharField
    """
    name = models.CharField(max_length=255, unique=True)
    url = models.CharField(max_length=255)

    def __unicode__(self):
        return unicode(self.name)


class Publication(models.Model):
    title = models.CharField(max_length=80)
#    slug = models.SlugField(unique=True)
    content = models.TextField()
#    firstauthor = models.CharField(max_length=256)
#    bibtype = models.CharField(max_length=256)
#    authors = models.CharField(max_length=2048)
#    year = models.IntegerField()
#    bibitem = models.TextField()
#    category = models.ForeignKey(Category)
#    abstract = models.TextField()
#    month = models.CharField(max_length=20, blank=True, null=True)
#    journal = models.CharField(max_length=256, blank=True, null=True)
#    number = models.CharField(max_length=256, blank=True, null=True)
#    institution = models.CharField(max_length=256, blank=True, null=True)
#    subcategory = models.ForeignKey('self', blank=True, null=True)
#    editor = models.CharField(max_length=2048, blank=True, null=True)
#    publisher = models.CharField(max_length=256, blank=True, null=True)
#    booktitle = models.CharField(max_length=256, blank=True, null=True)
#    pages = models.CharField(max_length=256, blank=True, null=True)
#    pdf = models.CharField(max_length=256, blank=True, null=True)
#    ps = models.CharField(max_length=256, blank=True, null=True)
#    url = models.CharField(max_length=256, blank=True, null=True)
#    note = models.CharField(max_length=256, blank=True, null=True)
#    pubtype = models.CharField(max_length=256, blank=True, null=True)
#    school = models.CharField(max_length=256, blank=True, null=True)
#    dataset = models.CharField(max_length=256, blank=True, null=True)
#    address = models.CharField(max_length=256, blank=True, null=True)

    class Meta:
        ordering = ('title', )

    def __unicode__(self):
        return self.title



class Repository(models.Model):
    """Base class for Repository items: Data, Task, Solution

    @cvar pub_date: publication date (item creation date)
    @type pub_date: models.DateTimeField
    @cvar version: version number to flip between different incarnations of the item
    @type version: integer / models.IntegerField
    @cvar name: item's name
    @type name: string / models.CharField
    @cvar slug: item's slug
    @type slug: string / Slug
    @cvar summary: item's summary
    @type summary: string / models.CharField
    @cvar description: item's description
    @type description: string / models.TextField
    @cvar urls: URLs linking to more information about item
    @type urls: string / models.CharField
    @cvar publications: publications where item is mentioned or used
    @type publications: models.ManyToManyField
    @cvar is_public: if item is public
    @type is_public: boolean / models.BooleanField
    @cvar is_deleted: if item is deleted
    @type is_deleted: boolean / models.BooleanField
    @cvar is_current: if item is the current one
    @type is_current: boolean / models.BooleanField
    @cvar user: user who created the item
    @type user: Django User
    @cvar rating_avg: item's average overal rating
    @type rating_avg: float / models.FloatField
    @cvar rating_avg_interest: item's average interesting rating
    @type rating_avg_interest: float / models.FloatField
    @cvar rating_avg_doc: item's average documentation rating
    @type rating_avg_doc: float / models.FloatField
    @cvar rating_votes: item's total number of rating votes
    @type rating_votes: integer / models.IntegerField
    """
    pub_date = models.DateTimeField()
    version = models.IntegerField(default=1)
    name = models.CharField(max_length=32)
    slug = models.ForeignKey(Slug)
    summary = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)
    urls = models.CharField(max_length=255, blank=True)
    publications = models.ManyToManyField(Publication, blank=True)
    is_public = models.BooleanField(default=True)
    is_deleted = models.BooleanField(default=False, editable=False)
    is_current = models.BooleanField(default=False, editable=False)
    user = models.ForeignKey(User, related_name='repository_user')
    rating_avg = models.FloatField(editable=False, default=-1)
    rating_avg_interest = models.FloatField(editable=False, default=-1)
    rating_avg_doc = models.FloatField(editable=False, default=-1)
    rating_votes = models.IntegerField(editable=False, default=0)
    downloads = models.IntegerField(editable=False, default=0)
    hits = models.IntegerField(editable=False, default=0)

    class Meta:
        """Inner meta class to specify options.

        @cvar ordering: default ordering of items in queries
        @type ordering: list
        @cvar get_latest_by: latestness will be determined by this field
        @type get_latest_by: string
        """
        ordering = ('-pub_date', )
        get_latest_by = 'pub_date'

    @classmethod
    def get_current_tagged_items(cls, user, tag):
        """Get current items with specific tag.

        @param user: user to get current items for
        @type user: auth.models.user
        @param tag: tag to get tagged items for
        @type tag: tagging.Tag
        @return: current tagged items
        @rtype: list of Data, Task or Solution
        """
        # without if-construct sqlite3 barfs on AnonymousUser
        if user.id:
            qs = (Q(user=user) | Q(is_public=True)) & Q(is_current=True)
        else:
            qs = Q(is_public=True) & Q(is_current=True)
        qs = cls.get_query(qs)

        tagged = TaggedItem.objects.filter(tag=tag)
        current = cls.objects.filter(qs).order_by('name')
        items = []
        for c in current:
            for t in tagged:
                if t.object_id == c.id:
                    items.append(c)
                    break
        return items

    @classmethod
    def get_object(cls, slug_or_id, version=None):
        """Retrieves an item by slug or id

            @param slug_or_id: item's slug or id for lookup
            @type slug_or_id: string or integer
            @param version: specific version of the item to retrieve
            @type version: integer
            @return: found object or None
            @rtype: Repository
            """
        if version:
            obj = cls.objects.filter(slug__text=slug_or_id, is_deleted=False, version=version)
        else:
            obj = cls.objects.filter(slug__text=slug_or_id, is_deleted=False, is_current=True)

        if obj: # by slug
            obj = obj[0]
        else: # by id
            try:
                obj = cls.objects.get(pk=slug_or_id)
            except cls.DoesNotExist:
                return None
            if not obj or obj.is_deleted:
                return None

        return obj


    def __init__(self, * args, ** kwargs):
        super(Repository, self).__init__(*args, ** kwargs)
        self.pub_date = dt.now()

    def __unicode__(self):
        return unicode(self.name)

    def get_media_file_name(self):
        raise NotImplementedError

    @classmethod
    def get_query(cls, qs):
        """Get a query for the given query.

        This allows objects to add further query qualifications (currently,
        Data: &= Q(is_approved=True)
        """
        return qs

    def save(self):
        """Save item.

        Creates a slug if necessary.
        """
        if not self.slug_id:
            self.slug = self.make_slug()
        super(Repository, self).save()


    def delete(self):
        """Delete item.

        Delete the corresponding slug.
        """
        try:
            Slug.objects.get(pk=self.slug.id).delete()
        except Slug.DoesNotExist:
            pass


    def make_slug(self):
        """Make a slug generated for the item's name.

        @return: a slug
        @rtype: Slug
        @raise AttributeError: if item's name is not set
        """
        if not self.name:
            raise AttributeError, 'Attribute name is not set!'
        slug = Slug(text=slugify(self.name))
        slug.save()
        return slug


    def get_next_version(self):
        """Get next available version for this item.

        @return: next available version
        @rtype: integer
        """
        if not self.slug_id:
            raise AttributeError, 'Attribute slug is not set!'

solution/models.py
from django.db import models

from repository.models import Repository
from repository.models import Rating
from repository.models import FixedLicense

from task.models import Task

from tagging.fields import TagField
from tagging.models import Tag
from tagging.models import TaggedItem
from tagging.utils import calculate_cloud

from utils import slugify

from settings import SCOREPATH

# Create your models here.
class Solution(Repository):
    """Repository item Solution.

    @cvar feature_processing: item's feature processing
    @type feature_processing: string / models.TextField
    @cvar parameters: item's parameters
    @type parameters: string / models.CharField
    @cvar os: operating system used
    @type os: string / models.CharField
    @cvar code: computer source code to provide solution
    @type code: string / models.TextField
    @cvar software_packages: software packages needed for evaluation
    @type software_packages: string / models.TextField
    @cvar score: score file
    @type score: models.FileField
    @cvar task: related Task
    @type task: Task
    @cvar license: item's license
    @type license: FixedLicense
    @cvar tags: item's tags
    @type tags: string / tagging.TagField
    """
    feature_processing = models.TextField(blank=True)
    parameters = models.CharField(max_length=255, blank=True)
    os = models.CharField(max_length=255, blank=True)
    code = models.TextField(blank=True)
    software_packages = models.TextField(blank=True)
    score = models.FileField(upload_to=SCOREPATH)
    task = models.ForeignKey(Task)
    license = models.ForeignKey(FixedLicense, editable=False)
    tags = TagField() # tagging doesn't work anymore if put into base class


    def get_scorename(self):
        """Construct filename for score file.

        @return: filename for score file
        @rtype: string
        @raise AttributeError: if slug is not set.
        """
        if not self.slug_id:
            raise AttributeError, 'Attribute slug is not set!'

        suffix = self.score.name.split('.')[-1]

        return self.slug.text + '.' + suffix

    def get_completeness_properties(self):
        return ['tags', 'description', 'summary', 'urls', 'publications',
            'feature_processing', 'parameters', 'os', 'code',
            'software_packages', 'score']

class SolutionRating(Rating):
    """Rating for a Solution item."""
    repository = models.ForeignKey(Solution)

repository/forms/publication.py
from django import forms
from repository.models import Publication

class PublicationForm(forms.ModelForm):
    """Form used for publications."""
    id = forms.IntegerField()
    next = forms.CharField()

    class Meta:
        """Inner meta class to specify model options.

        @cvar model: model to use
        @type model: models.Publication
        """
        model = Publication

repository/forms/result.py
from django.db import transaction
from django import forms
from repository.models import Task, Challenge, Result, Method
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

class ResultForm(forms.ModelForm):
    task = forms.ModelChoiceField(queryset=None, required=True)
    challenge = forms.ModelChoiceField(queryset=None, required=False)
    method= forms.ModelChoiceField(queryset=None, required=True)
    output_file = forms.FileField(required=True)

    def __init__(self, *args, **kwargs):
        user=None
        if kwargs.has_key('request'):
            request = kwargs.pop('request')
        else:
            request = None

        super(ResultForm, self).__init__(*args, **kwargs)

        try:
            user=request.user
        except:
            user=None

        qs_task=Task().get_public_qs(user)
        self.fields['task'].queryset=Task.objects.filter(qs_task)
        qs_challenge=Challenge().get_public_qs(user)
        self.fields['challenge'].queryset=Challenge.objects.filter(qs_challenge)
        qs_method=Method().get_public_qs(user)
        self.fields['method'].queryset=Method.objects.filter(qs_method)

    class Meta:
        model = Result

@transaction.commit_on_success
def edit(request):
    if not request.user.is_authenticated():
        if request.method == 'POST':
            next = '?next=' + request.POST['next']
        else:
            next = ''
        return HttpResponseRedirect(reverse('user_signin') + next)

    if request.method == 'POST':
        # work around a peculiarity within django
        result = None
        id = int(request.POST['id'])
        if id > 0:
            try:
                result = Result.objects.get(pk=id)
                form = ResultForm(request.POST, instance=result)
            except Result.DoesNotExist:
                form = ResultForm(request.POST)
        else:
            form = ResultForm(request.POST)

        if form.is_valid():
            if not result:
                result = Result()
            result.content = form.cleaned_data['content']
            result.title = form.cleaned_data['title']
            result.save()
            return HttpResponseRedirect(form.cleaned_data['next'])
        else:
            info_dict['result_form'] = ResultForm(request)
            return render_to_response('method/item_edit.html', info_dict)
    return HttpResponseRedirect(reverse('repository_index'))

repository/templates/solution/item_edit.html
{% extends "repository/base.html" %}
{% load i18n %}

{% block title %}{% trans "Repository" %} :: {{ object.klass }} :: {% trans "Edit" %} :: {{ object.name }}{% endblock %}
{% block breadcrumbs %}<a href="{% url repository_index %}">{% trans "Repository" %}</a> / <a href="{% url solution_index %}">{% trans "Solution" %}</a> / {% trans "Edit" %} / <a href="{% url repository.views.solution.view_slug object.slug %}">{{ object.name }}</a>{% endblock %}

{% block extrahead %}
{% include "autocomplete.html" %}
<script type="text/javascript" src="/media/js/jquery/jquery-ui.min.js"></script>
<script type="text/javascript">
$(function() {
	$('.cancel').click(function() {
		window.history.back(-1);
	});

	$('#tabs-publications select').removeAttr('multiple');
	$('#tabs-publications select').prepend($("<option></option>").attr("value", 0).text('')); 
	$("#tabs-publications select option[value='0']").attr('selected', 'selected')
	$('#tabs-publications select').change(function() {
		id = $('#tabs-publications #id_publications').val()
		// trickery to use django's URL function
		url = "{% url repository.views.publication.get 0 %}"
		url = url.substr(0, url.length - 2) + id;
		$.getJSON(url, function(data){
			$('#tabs-publications #id_title').val(data[0].fields.title);
			$('#tabs-publications #id_content').val(data[0].fields.content);
			$('#tabs-publications #id_id').val(id);
		});
	});
	$('#tabs-publications #id_title').val('');
	$('#tabs-publications #id_content').val('');


	$('#tabs').tabs();

	validate = function() {
		error = false;
		remove_error(['name']);

		if (!$('#id_name').val()) error = append_error('name');

		return !error;
	};

	$('#form-edit').submit(function() {
		if (!validate()) return false;

		if ($('#id_keep_private').length != 0 && !$('#id_keep_private').is(':checked')) {
			return window.confirm('{% trans "WARNING: You are about to make this item public, it cannot be made private again!" %}');
		}
		return true;
	});

});
</script>
{% endblock %}

{% block content %}
<h2 class="title-01">{% trans "Edit" %} {{ object.name }} ({% if object.is_public %}{% trans "public" %}{% else %}{% trans "private" %}{% endif %})</h2>
<div class="in">
		{% if form.errors %}
		<div class="error">{% trans "There had been errors, please see below" %}.</div>
		{% endif %}
		<div id="tabs">
			<ul class="clearfix">
				<li><a title="{% trans "Primary attributes of item + download" %}" href="#tabs-summary">{% trans "Summary" %}</a></li>
				<li><a title="{% trans "Other attributes of item" %}" href="#tabs-more">{% trans "More Info" %}</a></li>
				<li><a title="{% trans "Add or edit a publication" %}" href="#tabs-publications">{% trans "Publications" %}</a></li>
			</ul>

			<form id="form-edit" action="{{ object.url_edit }}" method="post" enctype="multipart/form-data">
			<div id="tabs-summary"><dl>
				<dt><label for="id_summary">{% trans "Summary" %}</label> {{ form.summary.errors }}</dt>
				<dd>{{ form.summary }}</dd>
				<dt><label for="id_tags">{% trans "Tags" %}</label> {{ form.tags.errors }}</dt>
				<dd>{{ form.tags }}</dd>

				<dt><label for="id_feature_processing">{% trans "Feature Processing" %}</label> {{ form.feature_processing.errors }}</dt>
				<dd>{{ form.feature_processing }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dd>
				<dt><label for="id_parameters">{% trans "Parameters" %}</label> {{ form.parameters.errors }}</dt>
				<dd>{{ form.parameters }}</dd>
				<dt><label for="id_os">{% trans "Operating System" %}</label> {{ form.os.errors }}</dt>
				<dd>{{ form.os }}</dd>
				<dt><label for="id_code">{% trans "Code" %}</label> {{ form.code.errors }}</dt>
				<dd>{{ form.code }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dd>
				<dt><label for="id_software_packages">{% trans "Software Packages" %}</label> {{ form.software_packages.errors }}</dt>
				<dd>{{ form.software_packages }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dd>
				<input type="submit" id="post" name="post" class="submit" value="{% trans "Save" %}" /> <input type="button" id="cancel_summary" name="cancel_summary" class="submit cancel" value="{% trans "Cancel" %}" /> {% if not object.is_public %}{{ form.keep_private }} {% trans "Keep private" %}{% endif %}
			</dl></div><!-- /tabs-summary -->

			<div id="tabs-more"><dl>
				<dt><label for="id_description">{% trans "Description" %}</label> {{ form.description.errors }}</dt>
				<dd>{{ form.description }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dd>
				<dt><label for="id_urls">{% trans "URLs" %}</label> {{ form.urls.errors }}</dt>
				<dd>{{ form.urls }}</dd>
				<dt><label for="id_publications">{% trans "Publications" %}</label> {{ form.publications.errors }}</dt>
				<dd>{{ form.publications }}</dd>
				<input type="submit" id="post" name="post" class="submit" value="{% trans "Save" %}" /> <input type="button" id="cancel_more" name="cancel_more" class="submit cancel" value="{% trans "Cancel" %}" /> {% if not object.is_public %}{{ form.keep_private }} {% trans "Keep private" %}{% endif %}
			</dl></div><!-- /tabs-more -->
			</form>

			<div id="tabs-publications"><form method="post" action="{% url repository.views.publication.edit %}"><dl>
				<dt><label for="id_publications">{% trans "Select an existing publication to edit or leave it blank to create a new one" %}</label></dt>
				<dd>{{ form.publications }}</dd>
				<dt><label for="id_title">{% trans "Title" %}</label> {{ publication_form.title.errors }}</dt>
				<dd>{{ publication_form.title }}</dd>
				<dt><label for="id_content">{% trans "Content" %}</label> {{ publication_form.content.errors }}</dt>
				<dd>{{ publication_form.content }}</dd>
				<input type="hidden" name="next" id="id_next" value="{{ request.path }}#tabs-more" />
				<input type="hidden" name="id" id="id_id" value="0" />
				<input type="submit" class="submit" value="{% trans "Submit Publication" %}" /> <input type="button" id="cancel_publication" name="cancel_publication" class="submit cancel" value="{% trans "Cancel" %}" />
			</dl></form></div>
		</div><!-- /tabs -->
</div><!-- /in -->
{% endblock %}

repository/templates/solution/item_new.html
{% extends "repository/base.html" %}
{% load i18n %}

{% block title %}{% trans "Repository" %} :: {{ klass }} :: {% trans "New" %}{% endblock %}
{% block breadcrumbs %}<a href="{% url repository_index %}">{% trans "Repository" %}</a> / {{ klass }} / {% trans "New" %}{% endblock %}

{% block extrahead %}
{% include "autocomplete.html" %}
<script type="text/javascript" src="/media/js/jquery/jquery-ui.min.js"></script>
<script type="text/javascript">

$(function() {
	remove_error = function(errors) {
		$.each(errors, function (idx, val) {
			$('#error_' + val).remove();
		});
	}
	append_error = function(id) {
		$('label[for|=id_' + id + ']').append(
			'<span id="error_' + id + '" class="error">' + '{% trans "REQUIRED" %}' + '</span>');
		return true;
	}

	$('#tabs').tabs();

	validate = function() {
		error = false;
		remove_error(['name']);

		if (!$('#id_name').val()) error = append_error('name');

		return !error;
	};

	$('#form-new').submit(function() {
		if (!validate()) return false;

		if (!$('#id_keep_private').is(':checked')) {
			return window.confirm('{% trans "WARNING: You are about to make this item public, it cannot be made private again!" %}');
		}
	});

});
</script>
{% endblock %}

{% block content %}
<h2 class="title-01">{% trans "Submit new" %} {{ klass }}</h2>
<div class="in">
	{% trans "Supply only the description of your solution under the Summary tab. You can upload your outputs later on by editing. Additional information can be entered under More Info or later on by editing." %}

	<form id="form-new" action="{{ url_new }}" method="post" enctype="multipart/form-data">
	{% if form.errors %}<p class="error">{% trans "There were some errors, please see below" %}.</td>{% endif %}
		<div id="tabs">
			<ul class="clearfix">
				<li><a title="{% trans "Primary attributes of item + download" %}" href="#tabs-summary">{% trans "Summary" %}</a></li>
				<li><a title="{% trans "Other attributes of item" %}" href="#tabs-more">{% trans "More Info" %}</a></li>
			</ul>


			<div id="tabs-summary"><dl>
				<dt><label for="id_name">{% trans "Name" %}</label> * {{ form.name.errors }}</dt>
				<dd>{{ form.name }}<br />
				    <span class="helptext">{% trans "Come up with good name. <b>IT CANNOT BE CHANGED LATER ON!</b> The name will also be used for creating the 'slug', that is, the readable id for this item." %}</span></dd>

				<dt><label for="id_summary">{% trans "Summary" %}</label> {{ form.summary.errors }}</dt>
				<dd>{{ form.summary }}<br />
            <span class="helptext">{% trans "One-line summary of your solution" %}</span></dd>

				<dt><label for="id_tags">{% trans "Tags" %}</label> {{ form.tags.errors }}</dt>
				<dd>{{ form.tags }}<br />
				    <span class="helptext">{% trans "Space separated tags for your solution (see tag cloud on the right)." %}</span></dd>

				<dt><label for="id_feature_processing">{% trans "Feature Processing" %}</label> {{ form.feature_processing.errors }}</dt>
				<dd>{{ form.feature_processing }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dd>
				<dt><label for="id_parameters">{% trans "Parameters" %}</label> {{ form.parameters.errors }}</dt>
				<dd>{{ form.parameters }}</dd>
				<dt><label for="id_os">{% trans "Operating System" %}</label> {{ form.os.errors }}</dt>
				<dd>{{ form.os }}</dd>
				<dt><label for="id_code">{% trans "Code" %}</label> {{ form.code.errors }}</dt>
				<dd>{{ form.code }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dd>
				<dt><label for="id_software_packages">{% trans "Software Packages" %}</label> {{ form.software_packages.errors }}</dt>
				<dd>{{ form.software_packages }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dd>
			</dl></div><!-- /tabs-summary -->

			<div id="tabs-more"><dl>
				<dt><label for="id_description">{% trans "Description" %}</label> {{ form.description.errors }}</dt>
				<dd>{{ form.description }}<br /><span class="helptext">{% trans 'You may use <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a> here, but <b>raw HTML will be removed</b>' %}.</span></dd>
				<dt><label for="id_urls">{% trans "URLs" %}</label> {{ form.urls.errors }}</dt>
				<dd>{{ form.urls }}</dd>
				<dt><label for="id_publications">{% trans "Publications" %}</label> {{ form.publications.errors }}</dt>
				<dd>{{ form.publications }}</dd>
			</dl></div><!-- /tabs-more -->
		</div>

		<input type="submit" name="post" class="submit" value="{% trans "Submit" %}" /> {{ form.keep_private }} {% trans "Keep private" %}
	</form>

</div><!-- /in -->
{% endblock %}

repository/templates/solution/tags_view.html
{% extends "repository/base.html" %}
{% load i18n %}

{% block title %}{% trans "Repository" %} :: {% trans "Tags" %} :: {{ tag }}{% endblock %}
{% block breadcrumbs %}<a href="{% url repository.views.solution.index %}">{% trans "Repository" %}</a> / {% trans "Tags" %} / {{ klass }} / {{ tag }}{% endblock %}

{% block content %}
<h2 class="title-01">{{ klass }} {% trans "items tagged by" %} <strong>{{ tag }}</strong></h2>
<div class="in">
	<ul>{% for obj in objects %}
		<li><a title="{{ obj.summary }}" href="{{ obj.get_absolute_slugurl }}">{{ obj.name }}</a></li>
	{% endfor %}</ul>
</div><!-- /in -->
{% endblock %}