urls.py
from django.conf.urls import *
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import views

urlpatterns = patterns('',
    (r'^about/', include('about.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^forum/', include('forum.urls')),
    (r'^repository/', include('repository.urls')),

    # somewhat util
    #(r'^accounts/', include('registration.urls')),
    (r'^accounts/', include('django_authopenid.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^user/', include('user.urls')),
    (r'^datacite/', include('datacite.urls')),
    (r'^challenge/', include('challengeviewer.urls')),

    (r'^$', views.welcome),
)

if settings.DEBUG and not settings.PRODUCTION:
	urlpatterns += patterns('',(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media'}),)

user/urls.py
from django.conf.urls.defaults import *

# General softwares views.
urlpatterns = patterns('',
    (r'^$', 'user.views.show_user_list'),
    (r'^view/(?P<user_id>\d+)/$', 'user.views.show_user'),
    (r'^update/(?P<user_id>\d+)/$', 'user.views.update_user'),
)

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django_authopenid.models import UserAssociation
from openid.consumer import consumer

import re

attrs_dict = { 'class': 'required' }
username_re = re.compile(r'^\w+$')

class ChangeUserDetailsForm(forms.Form):
    """
    Form for registering a new user account.

    Validates that the password is entered twice and matches,
    and that the username is not already taken.

    """
    firstname = forms.CharField(max_length=30,
            widget=forms.TextInput(attrs=attrs_dict),
            label=u'First Name', required=False)
    lastname = forms.CharField(max_length=30,
            widget=forms.TextInput(attrs=attrs_dict),
            label=u'Last Name', required=False)
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict,
        max_length=200)),
        label=u'Email address')
    openid_url = forms.CharField(max_length=255,
            widget=forms.TextInput(attrs=attrs_dict),
            label=u'OpenID URL', required=False)
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict),
            label=u'Password', required=False)
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=attrs_dict),
            label=u'Password (again, to catch typos)', required=False)

    def clean_firstname(self):
        """
        Validates that the first is alphanumeric
        """
        if 'firstname' in self.cleaned_data:
            if self.cleaned_data['firstname'] and not username_re.search(self.cleaned_data['firstname']):
                raise forms.ValidationError(u'First name can only contain letters, numbers and underscores')
        return self.cleaned_data['firstname']

    def clean_lastname(self):
        """
        Validates that the lastname is alphanumeric
        """
        if 'firstname' in self.cleaned_data:
            if self.cleaned_data['lastname'] and not username_re.search(self.cleaned_data['lastname']):
                raise forms.ValidationError(u'Last name can only contain letters, numbers and underscores')
        return self.cleaned_data['lastname']

    def clean_username(self):
        """
        Validates that the username is alphanumeric and is not already
        in use.

        """
        if 'username' in self.cleaned_data:
            if not username_re.search(self.cleaned_data['username']):
                raise forms.ValidationError(u'Usernames can only contain letters, numbers and underscores')
            try:
                user = User.objects.get(username__exact=self.cleaned_data['username'])
            except User.DoesNotExist:
                return self.cleaned_data['username']
            raise forms.ValidationError(u'This username is already taken. Please choose another.')


    def clean_openid_url(self):
        """
        Validates that OpenID URL starts with 'http' and verifies that given
        ID exists.
        """
        item = self.cleaned_data['openid_url']
        if item:
            if not item.startswith('http'):
                raise forms.ValidationError(u'OpenID URL must start with "http"')

            # access OpenID provider to get verified identity_url
            # this looks winged...
            c = consumer.Consumer({}, None)
            try:
                c.begin(item)
                r = c.complete({}, item)
                item = r.identity_url
            except consumer.DiscoveryFailure, e:
                raise forms.ValidationError(e)

        return item



    def clean_password1(self):
        """
        Validates that a password is given if no OpenID URL is supplied.
        """
        if 'password1' in self.cleaned_data:
            pw = self.cleaned_data['password1']
        else:
            pw = None

        if not 'openid_url' in self.cleaned_data and not pw:
            raise forms.ValidationError(u'You must use a password when not supplying an OpenID URL')

        return pw


    def clean_password2(self):
        """
        Validates that the two password inputs match.

        """
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data and \
                self.cleaned_data['password1'] == self.cleaned_data['password2']:
                    return self.cleaned_data['password2']
        raise forms.ValidationError(u'You must type the same password each time')

    def save(self, u):
        u.first_name=self.cleaned_data['firstname']
        u.last_name=self.cleaned_data['lastname']
        u.email=self.cleaned_data['email']
        if self.cleaned_data['password1']:
            u.set_password(self.cleaned_data['password1'])
        u.save()

        # for some strange reason (primary key == openid_url != int?), a new
        # item is created when saving an existing one, so delete the old
        try:
            UserAssociation.objects.get(user=u).delete()
        except UserAssociation.DoesNotExist:
            pass
        finally:
            ua = UserAssociation(
                openid_url=self.cleaned_data['openid_url'],
                user=u
            )
            ua.save()

user/views.py
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404, render_to_response
from django.template import RequestContext
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden
from django_authopenid.models import UserAssociation

from user.forms import *



def show_user_list(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden()
    return ListView.as_view(request,
            paginate_by=10,
            queryset=User.objects.all(),
            template_name='user/user_list.html',
            extra_context={'section': 'accounts'})



def show_user(request, user_id):
    if not request.user.is_authenticated():
        return HttpResponseForbidden()

    entry = get_object_or_404(User, pk=user_id)
    if not request.user.is_superuser and not entry == request.user:
        return HttpResponseForbidden()

    try:
        entry.openid_url = UserAssociation.objects.get(user=entry).openid_url
    except UserAssociation.DoesNotExist:
        entry.openid_url = ''

    form = ChangeUserDetailsForm(initial={
        'firstname': entry.first_name,
        'lastname': entry.last_name,
        'email': entry.email,
        'openid_url': entry.openid_url,
        'password1': '',
        'password2': '',
    })

    entry.last_login = entry.last_login.__str__().split('.')[0]
    entry.date_joined = entry.date_joined.__str__().split('.')[0]

    return render_to_response(
        'user/user_detail.html',
        { 'object': entry, 'form' : form, 'section': 'accounts'},
        context_instance=RequestContext(request)
    )


def update_user(request, user_id):
    if not request.user.is_authenticated():
        return HttpResponseForbidden()

    entry = get_object_or_404(User, pk=user_id)
    if not request.user.is_superuser and not entry == request.user:
        return HttpResponseForbidden()

    try:
        entry.openid_url = UserAssociation.objects.get(user=entry).openid_url
    except UserAssociation.DoesNotExist:
        entry.openid_url = ''

    form = ChangeUserDetailsForm(initial={
        'firstname': entry.first_name,
        'lastname': entry.last_name,
        'email': entry.email,
        'openid_url': entry.openid_url,
        'password1': '',
        'password2': '',
    })

    if request.method == 'POST':
        form = ChangeUserDetailsForm(request.POST)
        if form.is_valid():
            form.save(entry)
            return render_to_response(
                'user/user_change_done.html',
                { 'object': entry, 'section': 'accounts'},
                context_instance=RequestContext(request)
            )

    return render_to_response(
        'user/user_detail.html',
        { 'object': entry, 'form' : form, 'section': 'accounts'},
        context_instance=RequestContext(request)
    )

user/templates/user/user_change_done.html
{% extends "base-2col.html" %}
{% load i18n %}

{% block sectionid %}login{% endblock %}
{% block title %}{% trans "User Change" %}{% endblock %}
{% block breadcrumbs %}{% trans "Accounts" %} / {% trans "Change" %} {{ user }}{% endblock %}

{% block content %}
<h2 class="title-01">{% trans "Change User details" %}</h2>
<div class="in">
<p>{% trans "Your user details were successfully updated. Click" %} <a href="{% url "user.views.show_user" object.pk %}">{% trans "here" %}</a> {% trans "to return to your user page" %}.</p>
</div><!-- /in -->
{% endblock %}

{% block aside %}
<h4 class="title-03">{% trans "Contents" %}</h4>

{% if user.is_superuser or user.is_staff %}
<h4 class="title-04">{% trans "Admin" %}</h4>
<ul id="subnav">
<li><a href="{% url "user.views.show_user_list" %}">{% trans "Show registered users" %}</a></li>
</ul>
{% endif %}
{% endblock %}

user/templates/user/user_detail.html
{% extends "base-2col.html" %}
{% load i18n %}

{% block sectionid %}accounts{% endblock %}
{% block title %}{% trans "User Details" %}{% endblock %}
{% block breadcrumbs %}{% trans "Accounts" %} / {% trans "View" %} {{ user }}{% endblock %}

{% block content %}
<h2 class="title-01">{% trans "Details for user" %} {{ object.username }}</h2>
<div class="in">
	<dl id="news">
		<dt>{% trans "Full Name" %}:</dt>
		<dd>{{ object.get_full_name }}</dd>

		<dt>{% trans "Email Address" %}:</dt>
		<dd>{{object.email}}</dd>

		<dt>{% trans "OpenID URL" %}:</dt>
		<dd><a href="{{object.openid_url}}">{{object.openid_url}}</a></dd>
	</dl>

	{% if forumsubscriptions %}
	<h3>{% trans "Current Forum Subscriptions" %}</h3>
	<table>
	<tr>
		<th>{% trans "Title" %}</th>
		<th>{% trans "Last Notified" %}</th>
		<th>{% trans "Action" %}</th>
	</tr>
	{% for subsc in forumsubscriptions %}
	<tr>
		<td> <a href="{{ subsc.url }}">{{ subsc.title }}</a></td>
		<td> {{ subsc.last_updated|date:"j F Y H:i:s" }}</td>
		<td> <a href="{{ subsc.get_unsubscribe_url }}">{% trans "Unsubscribe" %}</a></td>
	</tr>
	{% endfor %}
	</table>
	{% endif %}

	<h3 class="title-02">{% trans "Change User Details" %}</h3>
	{% if form.errors %}<p class="error">{% trans "Please correct the errors below" %}:</p>{% endif %}

	<form method="post" action="{% url "user.views.update_user" object.pk %}">
	<dl>
		<dt><label for="id_firstname">{% trans "First Name" %}:</label>{% if form.firstname.errors %} <span class="error">{{ form.firstname.errors|join:", " }}</span>{% endif %}</dt>
		<dd>{{ form.firstname|safe }}</dd>
		<dt><label for="id_lastname">{% trans "Last Name" %}:</label>{% if form.lastname.errors %} <span class="error">{{ form.lastname.errors|join:", " }}</span>{% endif %}</dt>
		<dd>{{ form.lastname|safe }}</dd>
		<dt><label for="id_email">{% trans "Email address" %}:</label>{% if form.email.errors %} <span class="error">{{ form.email.errors|join:", " }}</span>{% endif %}</dd>
		<dd>{{ form.email|safe }}</dd>
		<dt><label for="id_openid_url">{{ form.openid_url.label }}:</label>{% if form.openid_url.errors %} <span class="error">{{ form.openid_url.errors|join:", " }}</span>{% endif %}</dd>
		<dd>{{ form.openid_url|safe }}</dd>
		<dt><label for="id_password1">{% trans "Password" %}:</label>{% if form.password1.errors %} <span class="error">{{ form.password2.errors|join:", " }}</span>{% endif %}</dt>
		<dd>{{ form.password1|safe }}</dd>
		<dt><label for="id_password2">{% trans "Password (type again to catch any typos)" %}:</label>{% if form.password2.errors %} <span class="error">{{ form.password2.errors|join:", " }}</span>{% endif %}</dt>
		<dd>{{ form.password2|safe }}</dd>
		<dt><input type="submit" class="submit" value="{% trans "Update" %}" /></dt>
        {% csrf_token %}
	</dl>
	</form>
</div><!-- /in -->
{% endblock %}

{% block aside %}
<h4 class="title-03">{% trans "Contents" %}</h4>

<div class="in">
<dl id="news">
	<dt>{% trans "Viewing details of" %}:</dt>
	<dd>{{object.username}}</dd>

	<dt>{% trans "Last login" %}:</dt>
	<dd>{{object.last_login}}</dd>

	<dt>{% trans "Date joined" %}:</dt>
	<dd>{{object.date_joined}}</dd>
</dl>


{% if user.is_superuser or user.is_staff %}
<h4 class="title-04">{% trans "Admin" %}</h4>
<ul id="subnav">
<li><a href="{% url "user.views.show_user_list" %}">{% trans "Show registered users" %}</a></li>
</ul>
{% endif %}

</div><!-- /in -->

{% endblock %}

user/templates/user/user_list.html
{% extends "base-2col.html" %}
{% load i18n %}
{% load paginator %}

{% block sectionid %}browse{% endblock %}
{% block title %}{% trans "User List" %}{% endblock %}
{% block breadcrumbs %}{% trans "Accounts" %} / {% trans "List Users" %}{% endblock %}

{% block content %}
<h2 class="title-01">{% trans "List Users" %}</h2>
<div class="in">
	{% paginator 10 %}
	<table>
	<tr>
		<th>{% trans "Username" %}</th>
		<th>{% trans "Full name" %}</th>
		<th>{% trans "Email address" %}</th>
	</tr>
	{% for user in object_list %}
	<tr>
		<td><a href="{% url 'user.views.show_user' user.pk %}">{{ user.username }}</a></td>
		<td>{{ user.get_full_name }}</td>
		<td>{{ user.email }}</td>
	</tr>
	{% endfor %}
	</table>
	{% paginator 10 %}
</div><!-- /in -->
{% endblock %}

{% block aside %}
<h4 class="title-03">{% trans "Contents" %}</h4>
<div class="in">
{% trans "Viewing List of Users" %}
</div><!-- /in -->
{% endblock %}